name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - xlrd
  - openpyxl  
  - wordcloud
  - seaborn
  - folium
  - scipy
